language: node_js
node_js:
  - "0.10"
  - "0.11"
before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install
after_script:
  - cat test/coverage/lcov/lcov.info | codeclimate
script: gulp
